#include <iostream>
using namespace std;

int main()
{
    setlocale(0, "");


    int a = 12;
    int a1 = 2;
    int a2 = 22;
    int a3 = 13;
    int a4 = 42;
    int a5 = 14;
    int a6 = 152;
    int a7 = 123;
    int a8 = 1232;
    int a9 = 121;

    cout << "a = " << a << "| тип: int, размер 4б." << endl;
    cout << "a1= " << a1 << " | тип: int, размер 4б." << endl;
    cout << "a2= " << a2 << " | тип: int, размер 4б." << endl;
    cout << "a3= " << a3 << " | тип: int, размер 4б." << endl;
    cout << "a4= " << a4 << " | тип: int, размер 4б." << endl;
    cout << "a5= " << a5 << " | тип: int, размер 4б." << endl;
    cout << "a6= " << a6 << " | тип: int, размер 4б." << endl;
    cout << "a7= " << a7 << " | тип: int, размер 4б." << endl;
    cout << "a8= " << a8 << " | тип: int, размер 4б." << endl;
    cout << "a9 = " << a9 << "| тип: int, размер 4б." << endl;
    cout << endl;
    short s = 3;
    short s1 = 22;
    short s2 = 42;
    short s3 = 153;
    short s4 = 472;
    short s5 = 54;
    short s6 = 72;
    short s7 = 33;
    short s8 = 192;
    short s9 = 131;
    cout << endl;
    cout << " s =" << s << "| тип: short, размер 2б." << endl;
    cout << " s1=" << s1 << "| тип: short, размер 2б." << endl;
    cout << " s2=" << s2 << "| тип: short, размер 2б." << endl;
    cout << " s3=" << s3 << "| тип: short, размер 2б." << endl;
    cout << " s4=" << s4 << "| тип: short, размер 2б." << endl;
    cout << " s5=" << s5 << "| тип: short, размер 2б." << endl;
    cout << " s6=" << s6 << "| тип: short, размер 2б." << endl;
    cout << " s7=" << s7 << "| тип: short, размер 2б." << endl;
    cout << " s8=" << s8 << "| тип: short, размер 2б." << endl;
    cout << " s9= " << s9 << "| тип: short, размер 2б." << endl;
    cout << endl;
    long l = 312;
    long l1 = 223;
    long l2 = 222;
    long l3 = 14343;
    long l4 = 422;
    long l5 = 142;
    long l6 = 1542;
    long l7 = 121233;
    long l8 = 12322;
    long l9 = 11;
    cout << endl;
    cout << " l =" << l << "| тип: long, размер 4б." << endl;
    cout << " l1=" << l1 << "| тип: long, размер 4б." << endl;
    cout << " l2=" << l2 << "| тип: long, размер 4б." << endl;
    cout << " l3=" << l3 << "| тип: long, размер 4б." << endl;
    cout << " l4=" << l4 << "| тип: long, размер 4б." << endl;
    cout << " l5=" << l5 << "| тип: long, размер 4б." << endl;
    cout << " l6=" << l6 << "| тип: long, размер 4б." << endl;
    cout << " l7=" << l7 << "| тип: long, размер 4б." << endl;
    cout << " l8=" << l8 << "| тип: long, размер 4б." << endl;
    cout << " l9= " << l9 << "| тип: long, размер 4б." << endl;
    cout << endl;
    float f = 312.6;
    float f1 = 22.63;
    float f2 = 22.62;
    float f3 = 14.6343;
    float f4 = 42.62;
    float f5 = 14.62;
    float f6 = 15.642;
    float f7 = 12.61233;
    float f8 = 12.6322;
    float f9 = 11.6;
    cout << endl;
    cout << " f =" << f << "| тип: float, размер 4б." << endl;
    cout << " f1=" << f1 << "| тип: float, размер 4б." << endl;
    cout << " f2=" << f2 << "| тип: float, размер 4б." << endl;
    cout << " f3=" << f3 << "| тип: float, размер 4б." << endl;
    cout << " f4=" << f4 << "| тип: float, размер 4б." << endl;
    cout << " f5=" << f5 << "| тип: float, размер 4б." << endl;
    cout << " f6=" << f6 << "| тип: float, размер 4б." << endl;
    cout << " f7=" << f7 << "| тип: float, размер 4б." << endl;
    cout << " f8=" << f8 << "| тип: float, размер 4б." << endl;
    cout << " f9= " << f9 << "| тип: float, размер 4б." << endl;
    cout << endl;
    double d = 312.035;
    double d1 = 22.0353;
    double d2 = 22.0352;
    double d3 = 14.035343;
    double d4 = 42.0352;
    double d5 = 14.0352;
    double d6 = 15.03542;
    double d7 = 12.0351233;
    double d8 = 12.035322;
    double d9 = 11.035;
    cout << endl;
    cout << " d =" << d << "| тип:  double, размер 8б." << endl;
    cout << " d1=" << d1 << "| тип:  double, размер 8б." << endl;
    cout << " d2=" << d2 << "| тип:  double, размер 8б." << endl;
    cout << " d3=" << d3 << "| тип:  double, размер 8б." << endl;
    cout << " d4=" << d4 << "| тип:  double, размер 8б." << endl;
    cout << " d5=" << d5 << "| тип:  double, размер 8б." << endl;
    cout << " d6=" << d6 << "| тип:  double, размер 8б." << endl;
    cout << " d7=" << d7 << "| тип:  double, размер 8б." << endl;
    cout << " d8=" << d8 << "| тип:  double, размер 8б." << endl;
    cout << " d9= " << d9 << "| тип:  double, размер 8б." << endl;
    cout << endl;
    char ch = 'w';
    char ch1 = 'e';
    char ch2 = 'r';
    char ch3 = 'b';
    char ch4 = 'c';
    char ch5 = 'n';
    char ch6 = 'k';
    char ch7 = 'l';
    char ch8 = 'y';
    char ch9 = 'o';
    cout << endl;
    cout << "ch = " << ch << " | тип: char, размер 1б." << endl;
    cout << "ch1= " << ch1 << "  | тип: char, размер 1б." << endl;
    cout << "ch2= " << ch2 << "  | тип: char, размер 1б." << endl;
    cout << "ch3= " << ch3 << "  | тип: char, размер 1б." << endl;
    cout << "ch4= " << ch4 << "  | тип: char, размер 1б." << endl;
    cout << "ch5= " << ch5 << "  | тип: char, размер 1б." << endl;
    cout << "ch6= " << ch6 << "  | тип: char, размер 1б." << endl;
    cout << "ch7= " << ch7 << "  | тип: char, размер 1б." << endl;
    cout << "ch8= " << ch8 << "  | тип: char, размер 1б." << endl;
    cout << "ch9 = " << ch9 << " | тип: char, размер 1б." << endl;
    cout << endl;
    bool g_1 = true;
    bool g_2 = true;
    bool g_3 = true;
    bool g_4 = true;
    bool g_5 = true;
    bool g_6 = false;
    bool g_7 = false;
    bool g_8 = false;
    bool g_9 = false;
    bool g_10 = false;
    cout << endl;
    cout << "g_1 = " << g_1 << " | тип: bool, размер 1б." << endl;
    cout << "g_2 = " << g_2 << " | тип: bool, размер 1б." << endl;
    cout << "g_3 = " << g_3 << " | тип: bool, размер 1б." << endl;
    cout << "g_4 = " << g_4 << " | тип: bool, размер 1б." << endl;
    cout << "g_5 = " << g_5 << " | тип: bool, размер 1б." << endl;
    cout << "g_6 = " << g_6 << " | тип: bool, размер 1б." << endl;
    cout << "g_7 = " << g_7 << " | тип: bool, размер 1б." << endl;
    cout << "g_8 = " << g_8 << " | тип: bool, размер 1б." << endl;
    cout << "g_9 = " << g_9 << " | тип: bool, размер 1б." << endl;
    cout << "g_10 = " << g_10 << " | тип: bool, размер 1б." << endl;

}